# Prelim Activity 3 Part 2
- DOMINGUEZ, Harry Jr
- LAPIG, Cazandra Jae

In [35]:
import pandas as pd

shows = pd.read_csv("data/shows.csv")
shows

,Rank,Peak,All Time Peak,Actual gross,Actual gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],NaN,NaN,Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,NaN,NaN,Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,NaN,NaN,Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

### Clean the dataset.
- Drop irrelevant columns
- Re-arrange columns
- Convert monetary values to integer values

In [36]:
# Drop irrelevant columns
shows = shows.drop(columns=['Peak', 'All Time Peak', 'Ref.'])

# Re-arrange columns to better display data
shows = shows[['Rank', 'Tour title', 'Artist', 'Year(s)', 'Shows', 'Actual gross', 'Actual gross (in 2022 dollars)', 'Average gross']]

# Function to remove the dollar signs ($) and commas (,)
# Also type casts the cleaned value to an integer
def clean_monetary_value(num):
    if type(num) is None:
        return None
    if type(num) is int:
        return num
    cleaned_num = num.replace(',', '')
    cleaned_num = cleaned_num.replace('$', '')
    return int(cleaned_num)

# Clean numeric fields and convert to Integers
shows['Actual gross'] = shows['Actual gross'].apply(lambda x: clean_monetary_value(x) if pd.notna(x) and x != '' else x)
shows['Actual gross (in 2022 dollars)'] = shows['Actual gross (in 2022 dollars)'].apply(lambda x: clean_monetary_value(x) if pd.notna(x) and x != '' else x)
shows['Average gross'] = shows['Average gross'].apply(lambda x: clean_monetary_value(x) if pd.notna(x) and x != '' else x)
shows

,Rank,Tour title,Artist,Year(s),Shows,Actual gross,Actual gross (in 2022 dollars),Average gross
0,1,The Eras Tour †,Taylor Swift,2023–2024,56,780000000.0,780000000.0,13928571
1,2,Renaissance World Tour,Beyoncé,2023,56,579800000.0,579800000.0,10353571
2,3,Sticky & Sweet Tour ‡[4][a],Madonna,2008–2009,85,411000000.0,560622615.0,4835294
3,4,Beautiful Trauma World Tour,Pink,2018–2019,156,397300000.0,454751555.0,2546795
4,5,Reputation Stadium Tour,Taylor Swift,2018,53,345675146.0,402844849.0,6522173
5,6,The MDNA Tour,Madonna,2012,88,NaN,NaN,3467709
6,7,Taking Chances World Tour,Celine Dion,2008–2009,131,280000000.0,381932682.0,2137405
7,7,Summer Carnival †,Pink,2023–2024,41,257600000.0,257600000.0,6282927
8,9,The Formation World Tour,Beyoncé,2016,49,256084556.0,312258401.0,5226215
9,10,The 1989 World Tour,Taylor Swift,2015,85,250400000.0,309141878.0,2945882
10,11,The Mrs. Carter Show World Tour,Beyoncé,2013–2014,132,NaN,NaN,1735606
11,12,The Monster Ball Tour *,Lady Gaga,2009–2011,203,227400000.0,295301479.0,1118227
12,13,Prismatic World Tour,Katy Perry,2014–2015,151,204000000.0,251856802.0,1350993
13,14,Living Proof: The Farewell Tour ‡[21][a],Cher,2002–2005,325,200000000.0,299676265.0,615385
14,15,Confessions Tour,Madonna,2006,60,194000000.0,281617035.0,3233333
15,16,The Truth About Love Tour,Pink,2013–2014,142,184000000.0,227452347.0,1295775
16,17,Born This Way Ball,Lady Gaga,2012–2013,98,170000000.0,213568571.0,1734694
17,18,Rebel Heart Tour,Madonna,2015–2016,82,169800000.0,207046755.0,2070732
18,19,Adele Live 2016,Adele,2016–2017,121,NaN,NaN,1385950
19,20,The Red Tour,Taylor Swift,2013–2014,86,150000000.0,185423109.0,1744186

### Imputation

Perform data imputation on the missing values in the dataset. Specifically:
- Row 6
- Row 11
- Row 19

...on the `Actual Gross`, `Actual Gross (in 2022 dollars)`, and `Average Gross` columns

In [37]:
# Imputate values for rows at index 5, 10, and 18
# Actual gross values
shows.loc[5, 'Actual gross'] = 305_200_000
shows.loc[10, 'Actual gross'] = 229_700_000
shows.loc[18, 'Actual gross'] = 278_442_753

# Actual gross (in 2022 dollars) values
shows.loc[5, 'Actual gross (in 2022 dollars)'] = int(shows['Actual gross'][5] * 1.29)
shows.loc[10, 'Actual gross (in 2022 dollars)'] = int(shows['Actual gross'][10] * 1.20)
shows.loc[18, 'Actual gross (in 2022 dollars)'] = int(shows['Actual gross'][18] * 1.34)

# Average gross values
shows.loc[5, 'Average gross'] = int(shows['Actual gross (in 2022 dollars)'][5] / int(shows['Shows'][5]))
shows.loc[10, 'Average gross'] = int(shows['Actual gross (in 2022 dollars)'][10] / int(shows['Shows'][10]))
shows.loc[18, 'Average gross'] = int(shows['Actual gross (in 2022 dollars)'][18] / int(shows['Shows'][18]))
shows

,Rank,Tour title,Artist,Year(s),Shows,Actual gross,Actual gross (in 2022 dollars),Average gross
0,1,The Eras Tour †,Taylor Swift,2023–2024,56,780000000.0,780000000.0,13928571
1,2,Renaissance World Tour,Beyoncé,2023,56,579800000.0,579800000.0,10353571
2,3,Sticky & Sweet Tour ‡[4][a],Madonna,2008–2009,85,411000000.0,560622615.0,4835294
3,4,Beautiful Trauma World Tour,Pink,2018–2019,156,397300000.0,454751555.0,2546795
4,5,Reputation Stadium Tour,Taylor Swift,2018,53,345675146.0,402844849.0,6522173
5,6,The MDNA Tour,Madonna,2012,88,305200000.0,393708000.0,4473954
6,7,Taking Chances World Tour,Celine Dion,2008–2009,131,280000000.0,381932682.0,2137405
7,7,Summer Carnival †,Pink,2023–2024,41,257600000.0,257600000.0,6282927
8,9,The Formation World Tour,Beyoncé,2016,49,256084556.0,312258401.0,5226215
9,10,The 1989 World Tour,Taylor Swift,2015,85,250400000.0,309141878.0,2945882
10,11,The Mrs. Carter Show World Tour,Beyoncé,2013–2014,132,229700000.0,275640000.0,2088181
11,12,The Monster Ball Tour *,Lady Gaga,2009–2011,203,227400000.0,295301479.0,1118227
12,13,Prismatic World Tour,Katy Perry,2014–2015,151,204000000.0,251856802.0,1350993
13,14,Living Proof: The Farewell Tour ‡[21][a],Cher,2002–2005,325,200000000.0,299676265.0,615385
14,15,Confessions Tour,Madonna,2006,60,194000000.0,281617035.0,3233333
15,16,The Truth About Love Tour,Pink,2013–2014,142,184000000.0,227452347.0,1295775
16,17,Born This Way Ball,Lady Gaga,2012–2013,98,170000000.0,213568571.0,1734694
17,18,Rebel Heart Tour,Madonna,2015–2016,82,169800000.0,207046755.0,2070732
18,19,Adele Live 2016,Adele,2016–2017,121,278442753.0,373113289.0,3083580
19,20,The Red Tour,Taylor Swift,2013–2014,86,150000000.0,185423109.0,1744186

### Further cleaning

It seems that there is an error in the values for the `Rank` column and `Adele Live 2016` should not be in 19th place after adding the actual values for the gross

In [38]:
# Move Adele Tour to Rank 8 to fix ranking
shows = pd.concat([shows.iloc[:7], pd.DataFrame([shows.iloc[18]]), shows.iloc[7:]]).reset_index(drop=True)
shows = shows.drop(index=19).reset_index(drop=True)

# Fix Ranking values
for rank in range(19):
    shows.loc[rank, 'Rank'] = rank + 1

shows

,Rank,Tour title,Artist,Year(s),Shows,Actual gross,Actual gross (in 2022 dollars),Average gross
0,1,The Eras Tour †,Taylor Swift,2023–2024,56,780000000.0,780000000.0,13928571
1,2,Renaissance World Tour,Beyoncé,2023,56,579800000.0,579800000.0,10353571
2,3,Sticky & Sweet Tour ‡[4][a],Madonna,2008–2009,85,411000000.0,560622615.0,4835294
3,4,Beautiful Trauma World Tour,Pink,2018–2019,156,397300000.0,454751555.0,2546795
4,5,Reputation Stadium Tour,Taylor Swift,2018,53,345675146.0,402844849.0,6522173
5,6,The MDNA Tour,Madonna,2012,88,305200000.0,393708000.0,4473954
6,7,Taking Chances World Tour,Celine Dion,2008–2009,131,280000000.0,381932682.0,2137405
7,8,Adele Live 2016,Adele,2016–2017,121,278442753.0,373113289.0,3083580
8,9,Summer Carnival †,Pink,2023–2024,41,257600000.0,257600000.0,6282927
9,10,The Formation World Tour,Beyoncé,2016,49,256084556.0,312258401.0,5226215
10,11,The 1989 World Tour,Taylor Swift,2015,85,250400000.0,309141878.0,2945882
11,12,The Mrs. Carter Show World Tour,Beyoncé,2013–2014,132,229700000.0,275640000.0,2088181
12,13,The Monster Ball Tour *,Lady Gaga,2009–2011,203,227400000.0,295301479.0,1118227
13,14,Prismatic World Tour,Katy Perry,2014–2015,151,204000000.0,251856802.0,1350993
14,15,Living Proof: The Farewell Tour ‡[21][a],Cher,2002–2005,325,200000000.0,299676265.0,615385
15,16,Confessions Tour,Madonna,2006,60,194000000.0,281617035.0,3233333
16,17,The Truth About Love Tour,Pink,2013–2014,142,184000000.0,227452347.0,1295775
17,18,Born This Way Ball,Lady Gaga,2012–2013,98,170000000.0,213568571.0,1734694
18,19,Rebel Heart Tour,Madonna,2015–2016,82,169800000.0,207046755.0,2070732
19,20,The Red Tour,Taylor Swift,2013–2014,86,150000000.0,185423109.0,1744186

### Normalization

We can now compute for the normalized values of the Gross columns (`Actual gross`, `Actual gross (in 2022 dollars)`, `Average gross`)

In [39]:
# Compute Normalized Values
columns = ['Actual gross', 'Actual gross (in 2022 dollars)', 'Average gross']
normalized_shows = shows.copy()
normalized_shows[columns] = (normalized_shows[columns] - normalized_shows[columns].min()) / (normalized_shows[columns].max() - normalized_shows[columns].min())
normalized_shows

,Rank,Tour title,Artist,Year(s),Shows,Actual gross,Actual gross (in 2022 dollars),Average gross
0,1,The Eras Tour †,Taylor Swift,2023–2024,56,1.000000,1.000000,1.000000
1,2,Renaissance World Tour,Beyoncé,2023,56,0.682222,0.663290,0.731469
2,3,Sticky & Sweet Tour ‡[4][a],Madonna,2008–2009,85,0.414286,0.631036,0.316972
3,4,Beautiful Trauma World Tour,Pink,2018–2019,156,0.392540,0.452975,0.145075
4,5,Reputation Stadium Tour,Taylor Swift,2018,53,0.310595,0.365675,0.443680
5,6,The MDNA Tour,Madonna,2012,88,0.246349,0.350308,0.289831
6,7,Taking Chances World Tour,Celine Dion,2008–2009,131,0.206349,0.330503,0.114324
7,8,Adele Live 2016,Adele,2016–2017,121,0.203877,0.315670,0.185395
8,9,Summer Carnival †,Pink,2023–2024,41,0.170794,0.121392,0.425709
9,10,The Formation World Tour,Beyoncé,2016,49,0.168388,0.213320,0.346336
10,11,The 1989 World Tour,Taylor Swift,2015,85,0.159365,0.208079,0.175052
11,12,The Mrs. Carter Show World Tour,Beyoncé,2013–2014,132,0.126508,0.151733,0.110627
12,13,The Monster Ball Tour *,Lady Gaga,2009–2011,203,0.122857,0.184801,0.037770
13,14,Prismatic World Tour,Katy Perry,2014–2015,151,0.085714,0.111733,0.055254
14,15,Living Proof: The Farewell Tour ‡[21][a],Cher,2002–2005,325,0.079365,0.192159,0.000000
15,16,Confessions Tour,Madonna,2006,60,0.069841,0.161786,0.196643
16,17,The Truth About Love Tour,Pink,2013–2014,142,0.053968,0.070688,0.051106
17,18,Born This Way Ball,Lady Gaga,2012–2013,98,0.031746,0.047337,0.084075
18,19,Rebel Heart Tour,Madonna,2015–2016,82,0.031429,0.036368,0.109316
19,20,The Red Tour,Taylor Swift,2013–2014,86,0.000000,0.000000,0.084788

### Standardization
We can now compute for the standardized values of the Gross columns (`Actual gross`, `Actual gross (in 2022 dollars)`, `Average gross`)

In [40]:
# Compute Standardized Values
standardized_shows = shows.copy()
standardized_shows[columns] = (standardized_shows[columns] - standardized_shows[columns].mean()) / standardized_shows[columns].std(ddof=0)
standardized_shows

,Rank,Tour title,Artist,Year(s),Shows,Actual gross,Actual gross (in 2022 dollars),Average gross
0,1,The Eras Tour †,Taylor Swift,2023–2024,56,3.245819,2.961674,3.083236
1,2,Renaissance World Tour,Beyoncé,2023,56,1.910074,1.575787,1.986373
2,3,Sticky & Sweet Tour ‡[4][a],Madonna,2008–2009,85,0.783832,1.443031,0.293284
3,4,Beautiful Trauma World Tour,Pink,2018–2019,156,0.692425,0.710137,-0.408861
4,5,Reputation Stadium Tour,Taylor Swift,2018,53,0.347981,0.350813,0.810844
5,6,The MDNA Tour,Madonna,2012,88,0.077929,0.287563,0.182420
6,7,Taking Chances World Tour,Celine Dion,2008–2009,131,-0.090207,0.206048,-0.534468
7,8,Adele Live 2016,Adele,2016–2017,121,-0.100597,0.144996,-0.244167
8,9,Summer Carnival †,Pink,2023–2024,41,-0.239661,-0.654647,0.737440
9,10,The Formation World Tour,Beyoncé,2016,49,-0.249772,-0.276273,0.413225
10,11,The 1989 World Tour,Taylor Swift,2015,85,-0.287700,-0.297847,-0.286415
11,12,The Mrs. Carter Show World Tour,Beyoncé,2013–2014,132,-0.425811,-0.529764,-0.549571
12,13,The Monster Ball Tour *,Lady Gaga,2009–2011,203,-0.441157,-0.393658,-0.847167
13,14,Prismatic World Tour,Katy Perry,2014–2015,151,-0.597283,-0.694404,-0.775751
14,15,Living Proof: The Farewell Tour ‡[21][a],Cher,2002–2005,325,-0.623971,-0.363373,-1.001446
15,16,Confessions Tour,Madonna,2006,60,-0.664003,-0.488388,-0.198221
16,17,The Truth About Love Tour,Pink,2013–2014,142,-0.730724,-0.863344,-0.792692
17,18,Born This Way Ball,Lady Gaga,2012–2013,98,-0.824133,-0.959455,-0.658026
18,19,Rebel Heart Tour,Madonna,2015–2016,82,-0.825467,-1.004602,-0.554924
19,20,The Red Tour,Taylor Swift,2013–2014,86,-0.957574,-1.154292,-0.655113

### Discretization
We can now perform Discretization on the dataset by categorizing the Average Gross values

In [41]:
discretized_shows = shows.copy()
discretized_shows = discretized_shows.drop(columns=['Actual gross', 'Actual gross (in 2022 dollars)'])

def categorize_avg_gross(num):
    if(num > 10_000_000):
        return 'Very Consistent Viewership'
    elif(num > 5_000_000):
        return 'Steady Viewership'
    elif(num > 2_000_000):
        return 'Variable Viewership'

    return 'Inconsistent Viewership'

discretized_shows = discretized_shows.assign(Category=discretized_shows['Average gross'].apply(categorize_avg_gross))
discretized_shows

,Rank,Tour title,Artist,Year(s),Shows,Average gross,Category
0,1,The Eras Tour †,Taylor Swift,2023–2024,56,13928571,Very Consistent Viewership
1,2,Renaissance World Tour,Beyoncé,2023,56,10353571,Very Consistent Viewership
2,3,Sticky & Sweet Tour ‡[4][a],Madonna,2008–2009,85,4835294,Variable Viewership
3,4,Beautiful Trauma World Tour,Pink,2018–2019,156,2546795,Variable Viewership
4,5,Reputation Stadium Tour,Taylor Swift,2018,53,6522173,Steady Viewership
5,6,The MDNA Tour,Madonna,2012,88,4473954,Variable Viewership
6,7,Taking Chances World Tour,Celine Dion,2008–2009,131,2137405,Variable Viewership
7,8,Adele Live 2016,Adele,2016–2017,121,3083580,Variable Viewership
8,9,Summer Carnival †,Pink,2023–2024,41,6282927,Steady Viewership
9,10,The Formation World Tour,Beyoncé,2016,49,5226215,Steady Viewership
10,11,The 1989 World Tour,Taylor Swift,2015,85,2945882,Variable Viewership
11,12,The Mrs. Carter Show World Tour,Beyoncé,2013–2014,132,2088181,Variable Viewership
12,13,The Monster Ball Tour *,Lady Gaga,2009–2011,203,1118227,Inconsistent Viewership
13,14,Prismatic World Tour,Katy Perry,2014–2015,151,1350993,Inconsistent Viewership
14,15,Living Proof: The Farewell Tour ‡[21][a],Cher,2002–2005,325,615385,Inconsistent Viewership
15,16,Confessions Tour,Madonna,2006,60,3233333,Variable Viewership
16,17,The Truth About Love Tour,Pink,2013–2014,142,1295775,Inconsistent Viewership
17,18,Born This Way Ball,Lady Gaga,2012–2013,98,1734694,Inconsistent Viewership
18,19,Rebel Heart Tour,Madonna,2015–2016,82,2070732,Variable Viewership
19,20,The Red Tour,Taylor Swift,2013–2014,86,1744186,Inconsistent Viewership